a1 = input("Enter your name\n")
print()

print("Hello " + a1)
print("Bellow you will asked a set of Qustion please ans them ownestly.")
print("THANKYOU")
print()
# --------------------------
myDict1 = {
    "BGMI": '''BGMI
    Hello Battle Ground Mobile India Player
    ----------------------------------------
   
    If You Play BGMI FROM ATLESTLEST 2 YEARS then there are some questions for you.
    ''',
    "FREE FIRE": '''Free Fire
    Hello Free Fire Player
    ----------------------
    
Hello Free Fire player If you are playing Free Fire from atlest 2 year here are some questions for you
    ''',
       
}

a2 = input("Enter Your Favrate Game Name\n")
print("Your Favrate Game is ", myDict1.get(a2))
print()
# --------------------------
print("------------------------------------------------------------")
myDict2 = {

    "BGMI": {'Q1': 'What is the name of the company who made Battle Grounds Mobile India',
    'Q2': 'what is the name of the person who made bgmi/pubg(one person name)',
    'Q3': 'In which date was BGMI launch',
    'Q4': 'What is the total revenue generated by BGMI to its company per Annum(per year)',
    'Q5': 'The company who made BGMI made his first game which was a PC or Mobile game'},
    
    
    "FF": {'Q1': 'Which Company owns Free Fire?',
    'Q2': 'Who is the owner of the company who made Free Fire',
    'Q3': 'In which date was the game launched tell in DD-MM-YYYY',
    'Q4': 'How much money did the company earn per Annum(per year)',
     'Q5': 'The componey who made FF was insperid from which PC gaming company',},
}

print("Here wre your Question answer them in the bello formate")
print()
print(myDict2.get(a2))
print()
# --------------------------

q1 = input("Enter your Ans of Q1\n")

q2 = input("Enter your Ans of Q2\n")

q3 = input("Enter your Ans of Q3\n")

q4 = input("Enter your Ans of Q4\n")

q5 = input("Enter your Ans of Q5\n")
print()
# --------------------------

myDict3 = {
    5555: {'A1':'KRAFTON',
    'A2':'Brendan Greene',
    'A3':'02-07-2021',
    'A4':'BGMI procures 7 million overall revenue as of October 2021',
    'A5':'The First game was made on PC and its name was PUBG PC',},
    8888: {'F1':'Garena',
    'F2':'Forrest Li',
    'F3':'23-08-2017',
    'F4':'$86 million',
    'F5':'Mainly it get inspeird bu PUBG PC'},
    
}

print()
print("If You want to see the correct Ans then enter password below")
print()
b = input("Password\n")
b = int(b)

print(myDict3.get(5555))
print(myDict3.get(8888))