print("----------------------------------------------------------------")
print()
print("PERCENTAGE")
print()
a = input("Enter the number \n")
print()
b = input("Enter the persent\n")
print()
a = int(a)
b = int(b)
c = (a / b)* 100
print("Here is your persentage\n" , c)
print()
print("----------------------------------------------------------------")