print("ACCOUNTS")
print()
print("ENTER YOUR ACCOUNTS NUMBER WITH YOUR Roll No:                      Ex- 36  80   here first (30) represent Roll no. (80) represent marks obtain")
print("----------------------------------------------------------------")
print()
m1 = int(input("Enter your Accounts Number Roll No 1: "))
print()
m2 = int(input("Enter your Accounys Number Roll no 2: "))
print()
m3 = int(input("Enter your Accounys Number Roll no 3: "))
print()
m4 = int(input("Enter your Accounys Number Roll no 4: "))
print()
m5 = int(input("Enter your Accounys Number Roll no 5: "))
print()
print("------------------------------------------------------------")
t1 = [m1, m2, m3, m4, m5]
# print("------------------------------------------------------------")
print()
p1 = print("Roll No 1: ", m1)
p2 = print("Roll No 2: ", m2)
p3 = print("Roll No 3: ", m3)
p4 = print("Roll No 4: ", m4)
p5 = print("Roll No 5: ", m5)
print()
print("------------------------------------------------------------")